/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.JSONObject;
import utils.Utils;

/**
 *
 * @author lsilva
 */
public class DonationView extends javax.swing.JFrame {
    
    Socket connection;
    ObjectOutputStream saida;
    JFrame ReceptorList1;
    String txtusername;
    
    public DonationView(Socket connection, JFrame ReceptorList1, String txtusername) {
        this.connection = connection;
        this.ReceptorList1 = ReceptorList1;
        this.txtusername = txtusername;
        initComponents();
        this.setLocationRelativeTo(null);
        start();
    }
    
    public void start() {
        this.pack();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTValorDoacao = new javax.swing.JTextField();
        jCBAnonimo = new javax.swing.JCheckBox();
        jBEnviarDoacao = new javax.swing.JButton();
        jBCancelarDoacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);

        jLabel1.setText("Informe o valor da doação:");

        jTValorDoacao.setText("Digite o valor da doação");
        jTValorDoacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTValorDoacaoFocusGained(evt);
            }
        });

        jCBAnonimo.setText("Doação anonima");

        jBEnviarDoacao.setText("Doar");
        jBEnviarDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarDoacaoActionPerformed(evt);
            }
        });

        jBCancelarDoacao.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBEnviarDoacao)
                        .addGap(47, 47, 47)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jBCancelarDoacao))
                    .addComponent(jTValorDoacao, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jCBAnonimo)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTValorDoacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCBAnonimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEnviarDoacao)
                    .addComponent(jBCancelarDoacao))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEnviarDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarDoacaoActionPerformed
        
        JSONObject enviaDoacao = new JSONObject();
        JSONObject enviaDoacaoMessage = new JSONObject();
        enviaDoacao.put("protocol", 510);
        enviaDoacaoMessage.put("donor", Login.usernameglobal);
        enviaDoacaoMessage.put("receptor", txtusername);
        enviaDoacaoMessage.put("value", jTValorDoacao.getText());
        if (jCBAnonimo.isSelected()) {
            enviaDoacaoMessage.put("anonymous", true);
        } else {
            enviaDoacaoMessage.put("anonymous", false);
        }
        
        enviaDoacao.put("message", enviaDoacaoMessage);
        
        System.out.println("Enviado: " + enviaDoacao.toString());
        Utils.sendMessage(connection, enviaDoacao.toString());
        System.out.println("Enviou a mensagem");
        
        String messageJson = Utils.receiveMessage(connection);
        System.out.println("Recebeu");
        JSONObject jsonO = new JSONObject(messageJson);
        System.out.println("mensagem de resposta jsonO --->>>" + jsonO.toString());
        JSONObject messageO = new JSONObject(jsonO.optString("message"));
        System.out.println("mensagem de resposta messageO --->>>" + messageO.toString());
        Integer protocol = (Integer) jsonO.opt("protocol");
        
        if (protocol == 511) {
            JOptionPane.showMessageDialog(rootPane, "Doação efetuada com sucesso\n");
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro na doação.\nProcesso não efetivado\n");
            dispose();
        }

    }//GEN-LAST:event_jBEnviarDoacaoActionPerformed

    private void jTValorDoacaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTValorDoacaoFocusGained
        jTValorDoacao.setText("");
    }//GEN-LAST:event_jTValorDoacaoFocusGained

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelarDoacao;
    private javax.swing.JButton jBEnviarDoacao;
    private javax.swing.JCheckBox jCBAnonimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTValorDoacao;
    // End of variables declaration//GEN-END:variables
}
